name: Java CI with Javadoc (No Build Tools)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Puedes cambiar a 'zulu', 'adopt', etc.

      - name: Compile Java files
        run: mkdir -p build && javac -d build src/**/*.java

      - name: Run tests (if applicable)
        run: java -cp build org.junit.runner.JUnitCore com.example.MyTestClass  # Reemplaza con tu test

      - name: Generate Javadoc
        run: mkdir -p javadoc && javadoc -d javadoc -sourcepath src -subpackages com.example

      - name: Upload Javadoc as artifact
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: javadoc
