name: Java CI sin builds

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Crear directorios para archivos compilados
        run: mkdir -p out out_tests

      - name: Compilar código principal
        run: javac -d out $(find src -name "*.java")  # Compile main code
      - name: Compilar tests
        run: javac -d out_tests -cp out:libs/* $(find tests -name "*.java")  # Compile tests separately

      - name: Run tests
        run: java -cp .:libs/*:out org.junit.runner.JUnitCore $(find out -name "Test*.class" | sed 's|out/||' | sed 's|.class||' | tr '/' '.')

